name: wallman
description:  A dart library to get and set backgrounds on multiple GUI linux platforms.
version: 0.0.1
platforms:
  linux:

homepage: https://github.com/securearth/wallman

environment:
  sdk: '>=2.14.4 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

dependencies: 
  args: ^2.3.0 # Required for wlroots backend
  dbus: ^0.6.8 # Required for Gsettings backend
  gsettings: ^0.2.4 # Required for Gsettings backend
  ini: ^2.1.0 # Required for nitrogen backend
  path: ^1.8.1
